### ISSUE TITLE
Linux exception

### ISSUE THREAD

**Issue by zhum** [ngsankha/Panther#1]
Hello! I try to run Panther on Linux Ubuntu 12.04. When I start java -jar Panther, It starts, shown splashscreen and then error message in dialog window: java.lang.ClassNotFoundException: .....SubstanceRavenGraphiteGlassLookAndFeel.

I did not download source, but just compiled jar file.

**Comment by ngsankha** [comment]
@zhum Did you just download the compiled the `Panther.jar` file and try to run it? Then it will fail to run because there are dependencies on the other jar files as well. If you are downloading just the jar file make sure you get all the files in the `dist` folder.

**Comment by zhum** [comment]
O! That works!
Please, add short description into README file in dist folder.
